name:                MCTS
version:             0.1.0.0
github:              "jar2333/MCTS.hs"
license:             BSD3
author:              "Jose A. Ramos"
maintainer:          "jar2333@columbia.edu"
copyright:           "2022 Jose A. Ramos"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jar2333/MCTS.hs#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- parallel
- matrix
- random
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

library:
  source-dirs: src

executables:
  MCTS-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - MCTS


tests:
  MCTS-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MCTS
